apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myApp-external-secret
  namespace: myApp-dev
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: myApp-secret-store
    namespace: myApp
  
  target:
    name: myApp-secrets
    creationmyApp: Owner

  data:
  - secretKey: azureTEstSecretOne
    remoteRef:
      key: azureTEstSecretOne

  - secretKey: azureTEstSecretTwo
    remoteRef:
      key: azureTEstSecretTwo